Homework #1. Task #1. Волынец Арсений Викторович
vol0n/spbu_kotlin_hw pull request #1
Opened 2021-02-28 14:27 UTC by vol0n

2021-03-01 10:51 UTC, nbirillo requested changes

2021-03-01 10:51 UTC, nbirillo commented on src/main/kotlin/homework_1/task_1.kt
> +fun factorialRec(n: Int): Int = if (n <= 1) 1 else n * factorialRec(n - 1)
А где имя пакета?

2021-03-01 10:51 UTC, nbirillo commented on build.gradle.kts
> +    failFast = false // fail build on any finding
А зачем ты это поменял?)

2021-03-01 10:51 UTC, nbirillo commented on src/main/kotlin/homework_1/task_1.kt
> +fun factorialRec(n: Int): Int = if (n <= 1) 1 else n * factorialRec(n - 1)
А почему ты не используешь ее? Считай итеративной и рекурсивной версиями

2021-03-01 10:51 UTC, nbirillo commented on src/main/kotlin/homework_1/task_1.kt
> +    var res = n
Для 0 неверно сработает

2021-03-01 10:51 UTC, nbirillo commented on src/main/kotlin/homework_1/task_1.kt
> +val scan = java.util.Scanner(System.`in`)
Давай обойдемся без глобальных переменных

2021-03-01 13:05 UTC, vol0n commented on build.gradle.kts
> +    failFast = false // fail build on any finding
у меня было такое, что детект выдаёт ошибки я их пытался исправить, а ничего не происходило, поэтому я что-то менял и обратно забыл поставить failFast, исправлю)

2021-03-04 10:38 UTC, nbirillo approved these changes
Зачтено!

2021-03-04 10:38 UTC, merged