Homework #3. Task #2. Волынец Арсений
vol0n/spbu_kotlin_hw pull request #11
Opened 2021-03-29 16:39 UTC by vol0n

2021-03-30 21:20 UTC, cupertank requested changes
А где тесты на сериализацию/десериализацию?

2021-03-30 22:19 UTC, vol0n commented
Я их добавил ещё во второй домашке, они лежат в пакете homework2

2021-04-01 12:37 UTC, cupertank commented
Мне не нравится твой тест на readJSON.
Сделай отдельную функцию для параметров для него и давай на вход "path-to-JSON" и "expectedList", просто считай и сравни, не нужно усложнять. Просто я практически не понимаю что там происходит и так быть особо не должно

2021-04-01 14:33 UTC, cupertank requested changes

2021-04-01 14:33 UTC, cupertank commented on src/test/kotlin/homework2/PerformedCommandStorageTest.kt
> +        }
Зачем тебе для этого отдельная функция, у тебя же есть целый тест, унеси это в тест....
Тебе совсем необязательно делать параметризованный тест. Если ты хочешь проверить чтение в пустой и непустой PCS, то сделай два отдельных теста, просто эта функция выглядит вообще ни к чему. Не усложняй тесты

2021-04-01 14:45 UTC, vol0n commented on src/test/kotlin/homework2/PerformedCommandStorageTest.kt
> +        }
мне просто кажутся параметризованные тесты более удобными, что можно добавлять аргументы, а не создавать новую функцию, если нужно добавить тест, у меня два теста, но вдруг надо будет добавить)

2021-04-03 14:19 UTC, cupertank approved these changes

2021-04-03 14:19 UTC, merged