Homework #8. Tic Tac Toe. Волынец Арсений
vol0n/spbu_kotlin_hw pull request #17
Opened 2021-05-26 13:55 UTC by vol0n

2021-05-27 13:34 UTC, SpirinEgor requested changes
Игра работает, выглядит хорошо. Единственное, когда выбираю игру за нолики, то все равно хожу первым...

По реализации -- супер запутанного кода нет, но текущая реализация далека от MVC, кажется это будет сложно масштабировать на новые режимы/возможности. Ну и идея, что поле это какой-то глобальный одиночный режим просто ужас)

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/controllers/GameController.kt
> +            }
Еще можно `val resultMessage = "${player?.name} won!" ?: "It is a draw: nobody won!"`
Ну и да `resMes` не лучшее название

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/GameModel.kt
> +    private val board: List<MutableList<SimpleStringProperty>> = List(this.boardSize) { rowIndex ->
Как так вышло, что модель, которая отвечает за логику, знает где и как это поле будет отображаться?

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/GameModel.kt
> +        }
Так до бесконечности игроков можно добавлять?) Вроде как в крестиках-ноликах есть инвариант в 2 игрока

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/GameModel.kt
> +    }
Переочищать не выглядит хорошим решением. Если будут появляться новые сущности надо будет не забывать переинициализировать их тут. Гораздо лучше избавиться от object и сделать нормальный класс. Модель будет создаваться одна на игру со всеми нужными полями.

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/Player.kt
> +        GameModel.gameBoard.mapIndexed { i, row ->
Ну это совсем жесть. Лезть в какие-то глобальные состояния, чтобы узнать положение. Я уже вижу этот CheaterPlayer, который меняет это глобальное состояние, чтобы побеждать)

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/views/MenuScreen.kt
> +object RandomMode : GameMode {
Что же ты так эти object любишь. Делай нормальные классы)

2021-05-27 13:34 UTC, SpirinEgor commented on src/main/kotlin/hw8/views/MenuScreen.kt
> +    fun createPlayer(): Player
И тут тоже совсем нелогично. У тебя вдруг представления начали сами создавать игроков.

2021-05-27 15:35 UTC, vol0n commented on src/main/kotlin/hw8/model/Player.kt
> +        GameModel.gameBoard.mapIndexed { i, row ->
Ну там же GameModel.gameBoard возвращает ReadOnlyStringProperty, а их нельзя менять, поэтому читер не пройдет вроде)

2021-05-27 15:39 UTC, vol0n commented on src/main/kotlin/hw8/views/MenuScreen.kt
> +object RandomMode : GameMode {
Хорошо)

2021-05-27 16:08 UTC, vol0n commented on src/main/kotlin/hw8/model/GameModel.kt
> +    private val board: List<MutableList<SimpleStringProperty>> = List(this.boardSize) { rowIndex ->
не очень понимаю, что модель знает про то где и как поле будет отображаться, надо было сделать String вместо SimpleStringProperty или вообще Int? Модель же в любом случае должна предоставлять какое-то api, что у нее поменялась такая-то клетка на поле, я подумал что удобно использовать Property

2021-05-27 16:14 UTC, vol0n commented on src/main/kotlin/hw8/views/MenuScreen.kt
> +    fun createPlayer(): Player
тут я тоже не очень понял, надо переместить это в другой файл? Или нелогично, что представление создает игроков (в методе onUndock()), а этим лучше должен заниматься контроллер? Или это все сразу?)

2021-05-27 17:50 UTC, vol0n commented on src/main/kotlin/hw8/controllers/GameController.kt
> +            }
вроде так нельзя: Elvis operator (?:) always returns the left operand of non-nullable type String

2021-05-29 16:53 UTC, SpirinEgor requested changes
Ага, теперь выглядит гораздо лучше, хоть и есть несколько архитектурных замечаний. Теперь это даже можно адекватно расширить на сетевой режим -- реализовать Player, который ходит на сервер за ходом противника. Не самое лучшее решение, но рабочее и в домашке сойдет.

2021-05-29 16:53 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/GameModel.kt
> +    protected abstract val players: MutableList<Player>
А зачем мутабельным делать?

2021-05-29 16:53 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/Player.kt
> +        fun chooseRandomTurn(game: GameModel): Turn {
А в чем прикол 2 раза модель игры передавать? Да и вообще кажется, что должно быть наоборот -- игра знает про игроков. Ну то есть реален читер, который может обращаться напрямую к игре и подменять поле.

2021-05-29 16:56 UTC, vol0n commented on src/main/kotlin/hw8/model/GameModel.kt
> +    protected abstract val players: MutableList<Player>
чтобы можно порядок игроков менять, мне почему-то не хотелось порядок через конструктор передавать, наверное так все же лучше, а список сделать неизменяемым?

2021-06-04 08:44 UTC, SpirinEgor commented on src/main/kotlin/hw8/model/GameModel.kt
> +    protected abstract val players: MutableList<Player>
Ну у тебя на каждую желательно отдельный объект заводить, а не переиспользовать имеющийся. А так вообще заводить список под 2 игроков, мб проще поддерживать 2 переменные и совать их по необходимости

2021-06-04 15:37 UTC, SpirinEgor approved these changes
Очень классно вышло, адекватная таблица игроков и возможность посылать приглашения. Можешь потом в отдельный репо вынести и хвастаться :)

2021-06-04 16:51 UTC, nbirillo approved these changes
Да, мне в целом тоже все нравится

2021-06-04 16:51 UTC, merged