Homework #1. Task #2. Волынец Арсений Викторович
vol0n/spbu_kotlin_hw pull request #2
Opened 2021-02-28 18:56 UTC by vol0n

2021-03-01 11:06 UTC, nbirillo requested changes

2021-03-01 11:06 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +fun countOccurrences(where: String, what: String): Int =
Опять нет пакета. Плюс нужно ответвляться от мастера, а не от прошлой ветки. Так что поменяй исходную ветку, пожалуйста, чтобы тут (в этом пр) была только вторая задача.

2021-03-01 11:06 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
Если ты посмотришь на реализацию, то `substring` копирует строку, это плохо, так что давай поищем другой способ решить эту задачу)

2021-03-01 11:06 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +fun main() {
Если ввести две пустые строки, то будет ошибка

2021-03-01 11:06 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +fun main() {
Если первая строка пустая, а вторая нет - ошибка

2021-03-01 11:06 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +fun main() {
Если вторая строка пустая, а первая нет, то ошибка

2021-03-01 13:00 UTC, vol0n commented on src/main/kotlin/homework_1/task_2.kt
> +fun countOccurrences(where: String, what: String): Int =
Да, я сильно затупил с ветками. То есть я правильно понял, что сейчас HEAD направляю туда же, где и мастер, а потом создаю новую ветку, добавляю туда файл со исправленной второй задачей и делаю новый пр? Или можно как-то эту ветку ответвить и сделать потом просто сделать коммит и он после пуша будет в этом пр? Просто я перевелся и еще с гитом не особо подружился

2021-03-01 18:58 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +fun countOccurrences(where: String, what: String): Int =
Ну первый вариант работать будет, но так делать нежелательно) Попробуй использовать `git rebase` для начала

2021-03-03 20:28 UTC, vol0n commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
Вроде я все просмотрел по доступу к кускам коллекции(substring, slice, chunked, windowed), там везде создаётся новый объект, как-то без циклов решить не получается. Мне пришло в голову только написать функцию, которая принимает индекс, строку и подстроку, и она сравнивает есть совпадает ли кусок с текущего индекса в строке с подстрокой, а потом с помощью foldIndexed посчитать сумму. 

fun compareChunk(idx: Int, source: String, substr: String): Boolean {
    var i = idx
    var j = 0
    while (i < substr.length){
        if (source[i] != substr[j])
            return false
        i++; j++
    }
    return true;
}

fun countOccurrences(where: String, what: String): Int =
    where.foldIndexed(0) {idx, count, _ ->
        count + if (idx < where.length - what.length + 1 && compareChunk(idx, where, what)) 1 else 0
    }

Неужели есть способ это как-то красиво без циклов сделать?)

2021-03-03 20:29 UTC, vol0n commented on src/main/kotlin/homework_1/task_2.kt
> +fun main() {
А если подстрока пустая, то надо считать как в теории множеств, что пустое множество содержится в любом множестве?

2021-03-04 12:18 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
можешь посмотреть в сторону [windowed](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/windowed.html) например :)

2021-03-04 12:19 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +fun main() {
На твое усмотрение, главное обработать все случаи

2021-03-04 12:19 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
В котлине почти все можно сделать, не используя напрямую циклы

2021-03-04 16:29 UTC, vol0n commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
В windowed вроде List<String> возвращается, а с циклом можно без создания объектов обойтись)

2021-03-05 07:12 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
ну да, ну ты же попросил вариант как сделать красиво без циклов)

2021-03-05 07:12 UTC, nbirillo commented on src/main/kotlin/homework_1/task_2.kt
> +    where.substring(0, where.length - what.length + 1)
но ты довольно неплохо тоже предложил на самом деле если что)

2021-03-05 07:23 UTC, nbirillo requested changes

2021-03-05 07:23 UTC, nbirillo commented on src/main/kotlin/homework1/task_2.kt
> +fun main() {
Решение довольно красивые было бы, если бы ты его починил :)
![image](https://user-images.githubusercontent.com/8993915/110080529-a1a0b980-7d9b-11eb-82a4-657f6c232bdb.png)

2021-03-05 07:23 UTC, nbirillo commented on src/main/kotlin/homework1/task_2.kt
> +fun countOccurrences(where: String, what: String): Int {
Вообще в Котлине прикольно писать расширения, то есть в твоем случае:
```
fun String.countOccurrences(substr: String): Int { ... }
```

Это при вызове очень аккуратно и красиво читается и нельзя перепутать, что строка, а что подстрока. Это конечно дело вкуса, но часто выглядит симпатичнее обычных функций

2021-03-05 15:17 UTC, nbirillo approved these changes
зачтено

2021-03-05 15:17 UTC, merged