Homework #1. Task #3. Волынец Арсений Викторович
vol0n/spbu_kotlin_hw pull request #3
Opened 2021-02-28 19:17 UTC by vol0n

2021-03-01 12:08 UTC, nbirillo requested changes

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +interface Action {
Нет пакета

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +    override fun cancelAction(ls: MutableList<Int>) = ls.removeFirst().let {}
А зачем `let {}`?

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +    override fun cancelAction(ls: MutableList<Int>) = ls.removeLast().let {}
А зачем `let {}`?

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +        val validRange = 0..ls.lastIndex
У списка можно получить список индексов

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +class SwapAction(private val i: Int, private val j: Int, ls: MutableList<Int>) : Action {
Это же move, поэтому лучше `move` (нужно именно переместить, а не поменять)

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +            // throw Exception("Invalid range for SwapAction")
Ну ты либо принти, либо кидай ошибку) не надо оставлять закомментированым какое-то из действий

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +    init { ls.add(ls.size, elem) }
Можно просто `ls.add(elem)`, по дефолту в конец добавит

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +            ls.add(j, ls.removeAt(i))
Почему ты добавляешь индекс то?... Нужно ведь элемент с этой позиции переместить. Тот же коммента про  отмену действия

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +    private val data = emptyList<Action>().toMutableList()
Можно сразу создать: `mutableListOf<Action>()`

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +    fun cancelAction() = if (data.isEmpty()) println("No actions in the storage, nothing to cancel")
Оберни тело функции в {} 
сложно читать такое

2021-03-01 12:08 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +/* test
Ну можно раскомментировать))

2021-03-01 12:50 UTC, vol0n commented on src/main/kotlin/homework_1/task_3.kt
> +    override fun cancelAction(ls: MutableList<Int>) = ls.removeFirst().let {}
remove возвращает элемент и не совпадает тип возвращаемого значения с тем, что в интерфейсе указал

2021-03-01 12:51 UTC, vol0n commented on src/main/kotlin/homework_1/task_3.kt
> +/* test
там вроде детект ошибки кидает MagicNumber

2021-03-01 12:54 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +    override fun cancelAction(ls: MutableList<Int>) = ls.removeFirst().let {}
Просто смотрится странно. Возможно здесь было бы лучше использовать нотацию  со скобками:
```
override fun cancelAction(ls: MutableList<Int>) {
    ls.removeFirst()
}
```

2021-03-01 19:00 UTC, nbirillo commented on src/main/kotlin/homework_1/task_3.kt
> +/* test
а, действительно. ну можно для удобства завести константы с этими значениями тут вверху файла к примеру и использовать их. Потом научитесь писать тесты и таких проблем уже не будет) просто постоянно комментировать\убирать комменты неудобно

2021-03-05 07:34 UTC, nbirillo approved these changes
Зачтено!

2021-03-05 07:34 UTC, nbirillo commented on src/main/kotlin/homework1/task_3.kt
> +    }
Это не ошибка, просто комментарий, на будущее, можно еще вот так было (думала может нагуглишь сам):
`override fun cancelAction(ls: MutableList<Int>): Unit = run { ls.removeFirst() }`

2021-03-05 07:35 UTC, merged