Homework #2. Task #3. Волынец Арсений
vol0n/spbu_kotlin_hw pull request #6
Opened 2021-03-12 22:26 UTC by vol0n

2021-03-22 10:52 UTC, elena-lyulina requested changes

2021-03-22 10:52 UTC, elena-lyulina commented on src/main/kotlin/homework1/task_3.kt
>  fun main() {
А добавь, пожалуйста, показательные запуски readJson и toJson, как я должно проверять-то их :)
и давай мы не будем хранить все в одном месте: и Action, и PerformedCommandStorage, и main. В идеальном мире ты вот реализовал Action и PerformedCommandStorage, и другие люди могут ими пользоваться где-то в другом месте. И ты тоже можешь их использовать для своих каких-то целей (например, для показательного запуска в main), но тоже в **другом** месте, чтобы не мешать реализацию и свое личное использование в одном месте, так как другим разработчикам твой main тут ну вот вообще не нужен и даже мешает

2021-03-22 23:10 UTC, vol0n commented on src/main/kotlin/homework1/task_3.kt
>  fun main() {
Я разбил классы на файлы и вынес main отдельно, плюс добавил пару тестов

2021-03-23 10:04 UTC, elena-lyulina requested changes
стало почти идеально, еще немного осталось :)

2021-03-23 10:04 UTC, elena-lyulina commented on src/main/kotlin/homework2/main.kt
> +    log.toJSON("src/main/kotlin/homework2/ss.json")
эх, в тестах ресурсы используешь, а тут не используешь :с

2021-03-23 10:04 UTC, elena-lyulina commented on src/main/kotlin/homework2/main.kt
> +    log.toJSON("src/main/kotlin/homework2/ss.json")
нельзя класть не-source файлы в папочку с source (src)

2021-03-23 10:04 UTC, elena-lyulina commented on src/main/kotlin/homework2/main.kt
> +    log.toJSON("src/main/kotlin/homework2/ss.json")
но вообще раз появились тесты, то можно перенести туда еще один случай с toJson (в тестах есть только readJson), а main вообще убрать и не париться

2021-03-23 10:04 UTC, elena-lyulina commented on src/test/kotlin/homework2/PerformedCommandStorageTest.kt
> +        assertEquals(ls, l)
обычно в названиях параметров в assert используют actual / expected, чтобы было лучше понятно, что именно ты проверяешь
например, actualList и expectedList

во втором тесте тоже лучше поменять названия

2021-03-24 11:30 UTC, elena-lyulina approved these changes
Супер

2021-03-24 11:30 UTC, merged