Homework #3. Task #3. Волынец Арсений
vol0n/spbu_kotlin_hw pull request #8
Opened 2021-03-18 22:17 UTC by vol0n

2021-03-19 11:59 UTC, cupertank requested changes
Очень неплохо, так держать!!!

2021-03-19 11:59 UTC, cupertank commented on src/main/kotlin/homework3/task_3.kt
> +    }
Мне кажется, что можно просто взять Set от functions, записать его в классе, сравнить размер сета и исходного массива и вывести Warning. Просто твоя функция по удалению дубликатов выглядит как-то очень дико, да и назвать её стоило бы removeDuplicates

2021-03-19 11:59 UTC, cupertank commented on src/main/kotlin/homework3/task_3.kt
> +        if (config.functions !== null) {
Можно просто !=, так ты проверяешь ссылку, так не пишут как правило

2021-03-19 11:59 UTC, cupertank commented on src/test/kotlin/homework3/Task_3KtTest.kt
> +        val pathToResources = "./src/test/resources/homework3"
Такое никуда не годится, почитай про работу с ресурсами в Java/Kotlin'е

2021-03-19 11:59 UTC, cupertank commented on src/main/kotlin/homework3/task_3.kt
> +                file.writeTo(this)
Кажется у вас в примере строятся internal классы, а у тебя public, доработай

2021-03-19 11:59 UTC, cupertank commented on src/test/kotlin/homework3/Task_3KtTest.kt
> +            Arguments.of("yamlTest.yaml", "yamlTest.txt", "yamlTest")
Я предлагаю унифицировать все немного иначе. Сделай в ресурсах для каждого теста отдельную папку с говорящим названием, в каждой папке сделай config.yaml и expected.kt(txt). По-итогу в аргументы параметризованных тестов ты просто передашь название папок, а по-совместительству и название теста))

2021-03-19 11:59 UTC, cupertank commented on src/test/kotlin/homework3/Task_3KtTest.kt
> +        generateTestFile("$pathToResources/yamlConfigs/$testConfigName", "$pathToResources/GeneratedTests")
Не стоит писать в ресурсы, почитай про Temporary Directory в JUnit 5

2021-03-19 12:04 UTC, cupertank commented
Подмерджи ещё мастер, чтобы у тебя ещё тесты на винде были. Скорее всего ты увидишь как у тебя они упадут из-за хардкода пути))

2021-03-19 12:09 UTC, cupertank requested changes
У тебя абсолютно не запускаются тесты если что, у тебя пустая выдача, потому что ты не до конца настроил грэдл

2021-03-19 12:09 UTC, cupertank commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
Это должно быть testImplementation и у тебя не хватает junit-engine

2021-03-19 15:28 UTC, vol0n commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
у меня в homework3/task_3.kt есть импорт теста для генерации аннотации к функциям, если тут сделать testImplemention, то homework3/task_3.kt не будет компилиться

2021-03-19 15:34 UTC, vol0n commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
и почему не хватает junit-engine, он же теперь автоматически подключается, как я понял: https://stackoverflow.com/a/55084036

2021-03-19 20:29 UTC, vol0n commented
Не могу понять, почему тесты на винде падают, вроде же текст совпадает.

2021-03-29 14:45 UTC, cupertank requested changes
Готов поставить тебе полный балл если ты быстро поправишь всё

2021-03-29 14:45 UTC, cupertank commented on src/main/kotlin/homework3/task_3.kt
> +    var setOfFuncs: Set<Function> = emptySet()
Зачем тебе тут var ещё с дополнительным геттером. Сделай просто так: `val setOfFucns: Set<Function>`, а в init сделай ветку else где `setOfFuncs = emptySet()`

2021-03-29 14:45 UTC, cupertank commented on src/test/kotlin/homework3/Task_3KtTest.kt
> +                println("Chars are not equal: expected: ${expected[i]}, actual: ${actual[i]}")
Мне кажется, что это отладочная информация, так что убери её из тестов

2021-03-29 14:45 UTC, cupertank commented on src/test/resources/homework3/yamlConfigs/identicalFuncs.yaml
> +  - name: "backwardApply"
Мне кажется или всё что в папке yamlConfigs не используется в тестах?

2021-03-29 14:45 UTC, cupertank commented on src/test/resources/homework3/yamlConfigs/identicalFuncs.yaml
> +  - name: "backwardApply"
Если так, то убери их оттуда

2021-03-29 14:45 UTC, cupertank commented
Разрезолви конфликты ещё

2021-03-29 15:55 UTC, cupertank approved these changes

2021-03-29 15:55 UTC, merged